[project]
name = "odr-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lxml>=6.0.0",
    "mcp[cli]>=1.10.1",
    "pyxodr>=0.1.3",
    "scenariogeneration>=0.15.0",
]
